# Generated by Django 5.1.11 on 2025-08-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Skill Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Employee Skill',
                'verbose_name_plural': 'Employee Skills',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='available_for_incidents',
            field=models.BooleanField(default=False, help_text='Can be assigned to incident shifts (Monday-Friday, 8:00-17:00)', verbose_name='Available for Incidents'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='available_for_waakdienst',
            field=models.BooleanField(default=False, help_text='Can be assigned to on-call/standby shifts (evenings, nights, weekends)', verbose_name='Available for Waakdienst'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Skills possessed by this employee', related_name='employees', to='employees.employeeskill', verbose_name='Skills'),
        ),
    ]
