# Generated by Django 5.1.11 on 2025-08-07 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeskill_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringLeavePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(help_text="Descriptive name for this pattern (e.g., 'Monday Mornings Off')", max_length=100, verbose_name='Pattern Name')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], help_text='Which day of the week this pattern applies to', verbose_name='Day of Week')),
                ('frequency', models.CharField(choices=[('weekly', 'Every Week'), ('biweekly', 'Every 2 Weeks')], default='weekly', help_text='How often this pattern repeats', max_length=20, verbose_name='Frequency')),
                ('coverage_type', models.CharField(choices=[('full_day', 'Full Day (8:00-17:00)'), ('morning', 'Morning Only (8:00-12:00)'), ('afternoon', 'Afternoon Only (12:00-17:00)')], default='full_day', help_text='What part of the day is affected', max_length=20, verbose_name='Coverage Type')),
                ('pattern_start_date', models.DateField(help_text='Date when this pattern first applies (important for biweekly patterns)', verbose_name='Pattern Start Date')),
                ('effective_from', models.DateField(help_text='When this pattern becomes active', verbose_name='Effective From')),
                ('effective_until', models.DateField(blank=True, help_text='When this pattern expires (blank = permanent)', null=True, verbose_name='Effective Until')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this pattern is currently in effect', verbose_name='Is Active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this pattern', verbose_name='Notes')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_leave_patterns', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Recurring Leave Pattern',
                'verbose_name_plural': 'Recurring Leave Patterns',
                'ordering': ['employee__username', 'day_of_week', 'coverage_type'],
            },
        ),
    ]
