# Generated by Django 5.1.11 on 2025-10-01 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_required',
            field=models.BooleanField(default=False, help_text='Require MFA for this user', verbose_name='MFA Required'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[], default='employee', max_length=20, verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='MFALoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('failure_reason', models.CharField(blank=True, choices=[('invalid_token', 'Invalid Token'), ('expired_token', 'Expired Token'), ('too_many_attempts', 'Too Many Attempts'), ('device_not_verified', 'Device Not Verified')], max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA Login Attempt',
                'verbose_name_plural': 'MFA Login Attempts',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(help_text='Base32-encoded TOTP secret', max_length=32, verbose_name='Secret Key')),
                ('is_verified', models.BooleanField(default=False, help_text='Has the user verified this device?', verbose_name='Is Verified')),
                ('backup_codes', models.JSONField(default=list, help_text='List of one-time backup codes', verbose_name='Backup Codes')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Last Used')),
                ('device_name', models.CharField(default='Authenticator App', max_length=100, verbose_name='Device Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_device', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Two-Factor Device',
                'verbose_name_plural': 'Two-Factor Devices',
            },
        ),
    ]
