# Generated by Django 5.1.11 on 2025-10-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_mfa_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('employee', 'Employee'), ('team_lead', 'Team Lead'), ('scheduler', 'Scheduler'), ('manager', 'Manager'), ('admin', 'Administrator')], max_length=20, unique=True, verbose_name='Role')),
                ('can_view_own_shifts', models.BooleanField(default=True, verbose_name='Can View Own Shifts')),
                ('can_view_team_shifts', models.BooleanField(default=False, verbose_name='Can View Team Shifts')),
                ('can_view_all_shifts', models.BooleanField(default=False, verbose_name='Can View All Shifts')),
                ('can_create_shifts', models.BooleanField(default=False, verbose_name='Can Create Shifts')),
                ('can_edit_own_shifts', models.BooleanField(default=False, verbose_name='Can Edit Own Shifts')),
                ('can_edit_team_shifts', models.BooleanField(default=False, verbose_name='Can Edit Team Shifts')),
                ('can_delete_shifts', models.BooleanField(default=False, verbose_name='Can Delete Shifts')),
                ('can_request_swap', models.BooleanField(default=True, verbose_name='Can Request Swap')),
                ('can_approve_swap', models.BooleanField(default=False, verbose_name='Can Approve Swap')),
                ('can_view_all_swaps', models.BooleanField(default=False, verbose_name='Can View All Swaps')),
                ('can_request_leave', models.BooleanField(default=True, verbose_name='Can Request Leave')),
                ('can_approve_leave', models.BooleanField(default=False, verbose_name='Can Approve Leave')),
                ('can_view_team_leave', models.BooleanField(default=False, verbose_name='Can View Team Leave')),
                ('can_run_orchestrator', models.BooleanField(default=False, verbose_name='Can Run Orchestrator')),
                ('can_override_fairness', models.BooleanField(default=False, verbose_name='Can Override Fairness')),
                ('can_manual_assign', models.BooleanField(default=False, verbose_name='Can Manual Assign')),
                ('can_manage_team', models.BooleanField(default=False, verbose_name='Can Manage Team')),
                ('can_view_team_analytics', models.BooleanField(default=False, verbose_name='Can View Team Analytics')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='Can View Reports')),
                ('can_export_data', models.BooleanField(default=False, verbose_name='Can Export Data')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Can Manage Users')),
                ('can_assign_roles', models.BooleanField(default=False, verbose_name='Can Assign Roles')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('team_lead', 'Team Lead'), ('scheduler', 'Scheduler'), ('manager', 'Manager'), ('admin', 'Administrator')], default='employee', max_length=20, verbose_name='Role'),
        ),
    ]
