# Generated by Django 5.1.11 on 2025-10-01 10:01

from django.db import migrations


def create_default_role_permissions(apps, schema_editor):
    """Create default permissions for each role."""
    RolePermission = apps.get_model('users', 'RolePermission')
    
    # Employee permissions (basic)
    RolePermission.objects.create(
        role='employee',
        can_view_own_shifts=True,
        can_view_team_shifts=False,
        can_view_all_shifts=False,
        can_create_shifts=False,
        can_edit_own_shifts=False,
        can_edit_team_shifts=False,
        can_delete_shifts=False,
        can_request_swap=True,
        can_approve_swap=False,
        can_view_all_swaps=False,
        can_request_leave=True,
        can_approve_leave=False,
        can_view_team_leave=False,
        can_run_orchestrator=False,
        can_override_fairness=False,
        can_manual_assign=False,
        can_manage_team=False,
        can_view_team_analytics=False,
        can_view_reports=False,
        can_export_data=False,
        can_manage_users=False,
        can_assign_roles=False,
    )
    
    # Team Lead permissions
    RolePermission.objects.create(
        role='team_lead',
        can_view_own_shifts=True,
        can_view_team_shifts=True,
        can_view_all_shifts=False,
        can_create_shifts=False,
        can_edit_own_shifts=True,
        can_edit_team_shifts=False,
        can_delete_shifts=False,
        can_request_swap=True,
        can_approve_swap=True,
        can_view_all_swaps=False,
        can_request_leave=True,
        can_approve_leave=False,
        can_view_team_leave=True,
        can_run_orchestrator=False,
        can_override_fairness=False,
        can_manual_assign=False,
        can_manage_team=False,
        can_view_team_analytics=True,
        can_view_reports=False,
        can_export_data=False,
        can_manage_users=False,
        can_assign_roles=False,
    )
    
    # Scheduler permissions
    RolePermission.objects.create(
        role='scheduler',
        can_view_own_shifts=True,
        can_view_team_shifts=True,
        can_view_all_shifts=True,
        can_create_shifts=True,
        can_edit_own_shifts=True,
        can_edit_team_shifts=True,
        can_delete_shifts=False,
        can_request_swap=True,
        can_approve_swap=True,
        can_view_all_swaps=True,
        can_request_leave=True,
        can_approve_leave=False,
        can_view_team_leave=True,
        can_run_orchestrator=True,
        can_override_fairness=False,
        can_manual_assign=True,
        can_manage_team=False,
        can_view_team_analytics=True,
        can_view_reports=True,
        can_export_data=True,
        can_manage_users=False,
        can_assign_roles=False,
    )
    
    # Manager permissions
    RolePermission.objects.create(
        role='manager',
        can_view_own_shifts=True,
        can_view_team_shifts=True,
        can_view_all_shifts=True,
        can_create_shifts=True,
        can_edit_own_shifts=True,
        can_edit_team_shifts=True,
        can_delete_shifts=True,
        can_request_swap=True,
        can_approve_swap=True,
        can_view_all_swaps=True,
        can_request_leave=True,
        can_approve_leave=True,
        can_view_team_leave=True,
        can_run_orchestrator=True,
        can_override_fairness=True,
        can_manual_assign=True,
        can_manage_team=True,
        can_view_team_analytics=True,
        can_view_reports=True,
        can_export_data=True,
        can_manage_users=False,
        can_assign_roles=False,
    )
    
    # Admin permissions (full access)
    RolePermission.objects.create(
        role='admin',
        can_view_own_shifts=True,
        can_view_team_shifts=True,
        can_view_all_shifts=True,
        can_create_shifts=True,
        can_edit_own_shifts=True,
        can_edit_team_shifts=True,
        can_delete_shifts=True,
        can_request_swap=True,
        can_approve_swap=True,
        can_view_all_swaps=True,
        can_request_leave=True,
        can_approve_leave=True,
        can_view_team_leave=True,
        can_run_orchestrator=True,
        can_override_fairness=True,
        can_manual_assign=True,
        can_manage_team=True,
        can_view_team_analytics=True,
        can_view_reports=True,
        can_export_data=True,
        can_manage_users=True,
        can_assign_roles=True,
    )


def reverse_default_role_permissions(apps, schema_editor):
    """Remove default role permissions."""
    RolePermission = apps.get_model('users', 'RolePermission')
    RolePermission.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_role_permission_model'),
    ]

    operations = [
        migrations.RunPython(
            create_default_role_permissions,
            reverse_default_role_permissions
        ),
    ]
