# Generated by Django 5.2.5 on 2025-08-07 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End time for partial day leave (uses leave type default if blank)', null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Whether this is a recurring leave pattern', verbose_name='Is Recurring'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='parent_request',
            field=models.ForeignKey(blank=True, help_text='Reference to the original recurring request', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_requests', to='leaves.leaverequest', verbose_name='Parent Request'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='When the recurring pattern should end', null=True, verbose_name='Recurrence End Date'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='recurrence_type',
            field=models.CharField(choices=[('none', 'One-time'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom Pattern')], default='none', max_length=20, verbose_name='Recurrence Type'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Start time for partial day leave (uses leave type default if blank)', null=True, verbose_name='Start Time'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='conflict_handling',
            field=models.CharField(choices=[('full_unavailable', 'Full Unavailable - Blocks all shifts'), ('daytime_only', 'Daytime Only - Blocks day shifts, available for waakdienst'), ('no_conflict', 'No Conflict - Does not block any shifts')], default='full_unavailable', help_text='How this leave type affects shift availability', max_length=20, verbose_name='Conflict Handling'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End time for partial day leave (leave blank for full day)', null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Start time for partial day leave (leave blank for full day)', null=True, verbose_name='Start Time'),
        ),
    ]
