# Generated by Django 5.1.11 on 2025-10-02 10:27
#
# Performance Optimization Migration for Leaves
# Adds database indexes to improve query performance for leave requests
#
# Target: LeaveRequest model
# Improves: Calendar queries, conflict detection, approval workflows

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leaverequest_end_time_leaverequest_is_recurring_and_more'),
    ]

    operations = [
        # LeaveRequest indexes - for calendar and conflict detection
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(
                fields=['employee', 'start_date', 'end_date'],
                name='leave_emp_dates_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(
                fields=['status', 'start_date'],
                name='leave_status_start_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(
                fields=['leave_type', 'status'],
                name='leave_type_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(
                fields=['created'],
                name='leave_created_idx'
            ),
        ),
    ]
