version: '3.8'

volumes:
  team_planner_postgres_data:
  team_planner_redis_data:

networks:
  team_planner_network:
    driver: bridge

services:
  # Django with full repository clone
  django:
    image: python:3.12-slim
    container_name: team_planner_django
    depends_on:
      - postgres
      - redis
    volumes:
      - app_code:/app
    working_dir: /app
    environment:
      - USE_DOCKER=true
      - DEBUG=true
      - DATABASE_URL=postgres://teamplanner:securepassword123@postgres:5432/team_planner
      - REDIS_URL=redis://redis:6379/0
      - CELERY_FLOWER_USER=admin
      - CELERY_FLOWER_PASSWORD=admin123
      - EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
      - DJANGO_SETTINGS_MODULE=config.settings.local
    ports:
      - '8001:8000'
    networks:
      - team_planner_network
    restart: unless-stopped
    command: >
      bash -c "
        echo 'Setting up Team Planner application...' &&
        if [ ! -f 'manage.py' ]; then
          echo 'Installing git and cloning repository...' &&
          apt-get update && apt-get install -y git &&
          git clone https://github.com/crunchynapkin404/team_planner.git /tmp/repo &&
          cp -r /tmp/repo/* . &&
          rm -rf /tmp/repo &&
          echo 'Repository cloned successfully!'
        fi &&
        echo 'Installing Python dependencies...' &&
        pip install --upgrade pip &&
        pip install -r requirements/local.txt &&
        echo 'Running database migrations...' &&
        python manage.py migrate &&
        echo 'Starting Django development server...' &&
        python manage.py runserver 0.0.0.0:8000
      "

  # React frontend  
  frontend:
    image: node:20-alpine
    container_name: team_planner_frontend
    depends_on:
      - django
    volumes:
      - frontend_code:/app
    working_dir: /app
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    networks:
      - team_planner_network
    restart: unless-stopped
    command: >
      sh -c "
        echo 'Setting up frontend...' &&
        if [ ! -f 'package.json' ]; then
          echo 'Installing git and cloning repository...' &&
          apk add --no-cache git &&
          git clone https://github.com/crunchynapkin404/team_planner.git /tmp/repo &&
          cp -r /tmp/repo/frontend/* . &&
          rm -rf /tmp/repo &&
          echo 'Frontend code setup complete!'
        fi &&
        if [ -f 'vite.config.docker.ts' ]; then
          echo 'Using Docker-specific Vite configuration...' &&
          cp vite.config.docker.ts vite.config.ts
        fi &&
        echo 'Installing npm dependencies...' &&
        npm install &&
        echo 'Starting Vite development server...' &&
        npm run dev -- --host 0.0.0.0
      "

  postgres:
    image: postgres:15-alpine
    container_name: team_planner_postgres
    volumes:
      - team_planner_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=team_planner
      - POSTGRES_USER=teamplanner
      - POSTGRES_PASSWORD=securepassword123
    networks:
      - team_planner_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: team_planner_redis
    volumes:
      - team_planner_redis_data:/data
    networks:
      - team_planner_network
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:latest
    container_name: team_planner_mailpit
    ports:
      - "8025:8025"
    networks:
      - team_planner_network
    restart: unless-stopped

volumes:
  app_code:
  frontend_code:
