# Generated by Django 5.1.11 on 2025-08-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulingrule',
            name='shift_type',
            field=models.CharField(choices=[('incidents', 'Incidents'), ('incidents_standby', 'Incidents-Standby'), ('waakdienst', 'Waakdienst'), ('changes', 'Changes'), ('projects', 'Projects')], max_length=20, verbose_name='Shift Type'),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='shift_type',
            field=models.CharField(choices=[('incidents', 'Incidents'), ('incidents_standby', 'Incidents-Standby'), ('waakdienst', 'Waakdienst'), ('changes', 'Changes'), ('projects', 'Projects')], max_length=20, verbose_name='Shift Type'),
        ),
    ]
