# Generated by GitHub Copilot to add ShiftAuditLog table
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0004_exclusion_constraint_overlap"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="Modified")),
                (
                    "action",
                    models.CharField(
                        max_length=50,
                        choices=[
                            ("reassigned", "Reassigned"),
                            ("swap_approved", "Swap Approved"),
                        ],
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="shifts.shift",
                    ),
                ),
                (
                    "from_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        null=True,
                        blank=True,
                        verbose_name="From Employee",
                    ),
                ),
                (
                    "to_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        null=True,
                        blank=True,
                        verbose_name="To Employee",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_shift_audits",
                        to=settings.AUTH_USER_MODEL,
                        null=True,
                        blank=True,
                        verbose_name="Actor",
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        max_length=50,
                        blank=True,
                        help_text="Origin of change (swap/leave/admin/etc.)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift Audit Log",
                "verbose_name_plural": "Shift Audit Logs",
                "ordering": ["-created", "-id"],
            },
        ),
    ]
