# Generated by Django 5.1.11 on 2025-10-02 06:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_shift_audit_log'),
        ('teams', '0003_team_prefs_membership_fte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringShiftPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=200, verbose_name='Pattern Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('recurrence_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20, verbose_name='Recurrence Type')),
                ('weekdays', models.JSONField(blank=True, default=list, help_text='List of weekday numbers (0=Monday, 6=Sunday) for weekly patterns', verbose_name='Weekdays')),
                ('day_of_month', models.PositiveIntegerField(blank=True, help_text='Day of month (1-31) for monthly patterns', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Day of Month')),
                ('pattern_start_date', models.DateField(verbose_name='Pattern Start Date')),
                ('pattern_end_date', models.DateField(blank=True, help_text='Leave blank for no end date', null=True, verbose_name='Pattern End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('last_generated_date', models.DateField(blank=True, help_text='Last date shifts were generated for this pattern', null=True, verbose_name='Last Generated Date')),
                ('assigned_employee', models.ForeignKey(blank=True, help_text='Leave blank for unassigned pattern', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_shift_patterns', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Employee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shift_patterns', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_shift_patterns', to='teams.team', verbose_name='Team')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_patterns', to='shifts.shifttemplate', verbose_name='Shift Template')),
            ],
            options={
                'verbose_name': 'Recurring Shift Pattern',
                'verbose_name_plural': 'Recurring Shift Patterns',
                'ordering': ['-created'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='pattern_end_after_start')],
            },
        ),
    ]
