# Generated by Django 5.1.11 on 2025-10-02 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_recurringshiftpattern'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shifttemplate',
            options={'ordering': ['-is_favorite', '-usage_count', 'shift_type', 'name'], 'verbose_name': 'Shift Template', 'verbose_name_plural': 'Shift Templates'},
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='category',
            field=models.CharField(blank=True, help_text="Template category for organization (e.g., 'Weekend', 'Holiday', 'Standard')", max_length=50, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shift_templates', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='default_end_time',
            field=models.TimeField(blank=True, help_text='Suggested end time for this template', null=True, verbose_name='Default End Time'),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='default_start_time',
            field=models.TimeField(blank=True, help_text='Suggested start time for this template', null=True, verbose_name='Default Start Time'),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Mark as favorite for quick access', verbose_name='Favorite'),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or instructions', verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags for searchability and filtering', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this template has been used', verbose_name='Usage Count'),
        ),
    ]
