# Generated by Django 5.1.11 on 2025-10-02 10:21
#
# Performance Optimization Migration
# Adds database indexes to improve query performance on frequently accessed columns
#
# Target Models:
# - Shift: Improves calendar queries and schedule generation
# - SwapRequest: Improves approval workflows and history queries
# - LeaveRequest: Improves calendar display and conflict detection
# - RecurringShiftPattern: Improves pattern matching and generation
# - ShiftTemplate: Improves library searches and usage tracking

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0008_advanced_approval_rules'),
    ]

    operations = [
        # Shift model indexes - for calendar and schedule queries
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(
                fields=['start_datetime', 'end_datetime'],
                name='shifts_start_end_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(
                fields=['assigned_employee', 'start_datetime'],
                name='shifts_emp_start_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(
                fields=['template', 'start_datetime'],
                name='shifts_template_start_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(
                fields=['status', 'start_datetime'],
                name='shifts_status_start_idx'
            ),
        ),
        
        # SwapRequest model indexes - for approval workflows
        migrations.AddIndex(
            model_name='swaprequest',
            index=models.Index(
                fields=['status', 'created'],
                name='swap_status_created_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='swaprequest',
            index=models.Index(
                fields=['requesting_employee', 'status'],
                name='swap_req_emp_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='swaprequest',
            index=models.Index(
                fields=['target_employee', 'status'],
                name='swap_tgt_emp_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='swaprequest',
            index=models.Index(
                fields=['requesting_shift', 'status'],
                name='swap_req_shift_status_idx'
            ),
        ),
        
        # RecurringShiftPattern indexes - for pattern generation
        migrations.AddIndex(
            model_name='recurringshiftpattern',
            index=models.Index(
                fields=['is_active', 'pattern_start_date'],
                name='pattern_active_start_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='recurringshiftpattern',
            index=models.Index(
                fields=['template', 'is_active'],
                name='pattern_template_active_idx'
            ),
        ),
        
        # ShiftTemplate indexes - for library searches
        migrations.AddIndex(
            model_name='shifttemplate',
            index=models.Index(
                fields=['is_active', 'created'],
                name='template_active_created_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='shifttemplate',
            index=models.Index(
                fields=['category', 'is_active'],
                name='template_cat_active_idx'
            ),
        ),
        
        # SwapApprovalRule indexes - for rule matching
        migrations.AddIndex(
            model_name='swapapprovalrule',
            index=models.Index(
                fields=['is_active', 'priority'],
                name='approval_rule_active_priority_idx'
            ),
        ),
    ]
