# Generated by Django 5.1.11 on 2025-10-01 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Recipient Email')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('notification_type', models.CharField(blank=True, choices=[('shift_assigned', 'Shift Assigned'), ('shift_updated', 'Shift Updated'), ('shift_cancelled', 'Shift Cancelled'), ('swap_requested', 'Swap Requested'), ('swap_approved', 'Swap Approved'), ('swap_rejected', 'Swap Rejected'), ('leave_submitted', 'Leave Request Submitted'), ('leave_approved', 'Leave Request Approved'), ('leave_rejected', 'Leave Request Rejected'), ('schedule_published', 'Schedule Published'), ('reminder', 'Reminder'), ('system', 'System Notification')], max_length=30, null=True, verbose_name='Notification Type')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Sent At')),
                ('success', models.BooleanField(default=True, verbose_name='Success')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_shift_assigned', models.BooleanField(default=True, verbose_name='Email: Shift Assigned')),
                ('email_shift_updated', models.BooleanField(default=True, verbose_name='Email: Shift Updated')),
                ('email_shift_cancelled', models.BooleanField(default=True, verbose_name='Email: Shift Cancelled')),
                ('email_swap_requested', models.BooleanField(default=True, verbose_name='Email: Swap Requested')),
                ('email_swap_approved', models.BooleanField(default=True, verbose_name='Email: Swap Approved')),
                ('email_swap_rejected', models.BooleanField(default=True, verbose_name='Email: Swap Rejected')),
                ('email_leave_approved', models.BooleanField(default=True, verbose_name='Email: Leave Approved')),
                ('email_leave_rejected', models.BooleanField(default=True, verbose_name='Email: Leave Rejected')),
                ('email_schedule_published', models.BooleanField(default=True, verbose_name='Email: Schedule Published')),
                ('email_reminders', models.BooleanField(default=True, verbose_name='Email: Reminders')),
                ('inapp_shift_assigned', models.BooleanField(default=True, verbose_name='In-App: Shift Assigned')),
                ('inapp_shift_updated', models.BooleanField(default=True, verbose_name='In-App: Shift Updated')),
                ('inapp_shift_cancelled', models.BooleanField(default=True, verbose_name='In-App: Shift Cancelled')),
                ('inapp_swap_requested', models.BooleanField(default=True, verbose_name='In-App: Swap Requested')),
                ('inapp_swap_approved', models.BooleanField(default=True, verbose_name='In-App: Swap Approved')),
                ('inapp_swap_rejected', models.BooleanField(default=True, verbose_name='In-App: Swap Rejected')),
                ('inapp_leave_approved', models.BooleanField(default=True, verbose_name='In-App: Leave Approved')),
                ('inapp_leave_rejected', models.BooleanField(default=True, verbose_name='In-App: Leave Rejected')),
                ('inapp_schedule_published', models.BooleanField(default=True, verbose_name='In-App: Schedule Published')),
                ('inapp_reminders', models.BooleanField(default=True, verbose_name='In-App: Reminders')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='No notifications during quiet hours', null=True, verbose_name='Quiet Hours Start')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Quiet Hours End')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('shift_assigned', 'Shift Assigned'), ('shift_updated', 'Shift Updated'), ('shift_cancelled', 'Shift Cancelled'), ('swap_requested', 'Swap Requested'), ('swap_approved', 'Swap Approved'), ('swap_rejected', 'Swap Rejected'), ('leave_submitted', 'Leave Request Submitted'), ('leave_approved', 'Leave Request Approved'), ('leave_rejected', 'Leave Request Rejected'), ('schedule_published', 'Schedule Published'), ('reminder', 'Reminder'), ('system', 'System Notification')], max_length=30, verbose_name='Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('related_shift_id', models.IntegerField(blank=True, null=True, verbose_name='Related Shift ID')),
                ('related_leave_id', models.IntegerField(blank=True, null=True, verbose_name='Related Leave ID')),
                ('related_swap_id', models.IntegerField(blank=True, null=True, verbose_name='Related Swap ID')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Additional Data')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='Action URL')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['recipient', '-created'], name='notificatio_recipie_56ba46_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
    ]
