# Generated by Django 5.1.11 on 2025-10-02 10:50
#
# Performance Optimization Migration for Notifications
# Adds database indexes to improve query performance for notifications
#
# Target: Notification and NotificationPreference models
# Improves: Notification list queries, filtering, preference lookups

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        # Notification indexes - for notification list and filtering
        # Note: recipient/created and recipient/is_read already have indexes in model Meta
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(
                fields=['recipient', 'notification_type'],
                name='notif_recipient_type_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(
                fields=['is_read', 'created'],
                name='notif_read_created_idx'
            ),
        ),
        # No additional indexes needed for NotificationPreference
        # as it's queried primarily by user (OneToOneField with automatic index)
    ]
