# Generated by Django 5.1.11 on 2025-08-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestrationrun',
            name='incidents_standby_shifts_created',
            field=models.PositiveIntegerField(default=0, verbose_name='Incidents-Standby Shifts Created'),
        ),
        migrations.AddField(
            model_name='orchestrationrun',
            name='schedule_incidents',
            field=models.BooleanField(default=True, verbose_name='Schedule Incidents'),
        ),
        migrations.AddField(
            model_name='orchestrationrun',
            name='schedule_incidents_standby',
            field=models.BooleanField(default=False, verbose_name='Schedule Incidents-Standby'),
        ),
        migrations.AddField(
            model_name='orchestrationrun',
            name='schedule_waakdienst',
            field=models.BooleanField(default=True, verbose_name='Schedule Waakdienst'),
        ),
        migrations.AlterField(
            model_name='orchestrationresult',
            name='shift_type',
            field=models.CharField(choices=[('incidents', 'Incidents'), ('incidents_standby', 'Incidents-Standby'), ('waakdienst', 'Waakdienst')], max_length=20, verbose_name='Shift Type'),
        ),
    ]
